services:
  mushroom_expert:
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile-${DEVICE:-cpu}
      args:
        LLM_PATH: ${LLM_PATH:-huggingface}
    ports:
      - "8888:8888"
      - "7860:7860"
    volumes:
      - .:/home/jovyan/work
    stdin_open: true
    tty: true
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
